import { Component } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { MedicineService } from '../../services/medicine.service';
// import { Medicine } from '../../models/medicine.model';

@Component({
  selector: 'app-add',
  templateUrl: './add.component.html',
  styleUrls: ['./add.component.scss'],
  standalone: true,
  imports: [ReactiveFormsModule]
})
export class AddComponent {
  addForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    private medicineService: MedicineService,
    private router: Router
  ) {
    this.addForm = this.fb.group({
      name: ['', Validators.required],
      manufacturer: ['', Validators.required],
      price: [0, Validators.required],
      expiryDate: ['', Validators.required]
    });
  }

  addMedicine() {
    if (this.addForm.valid) {
      const newMedicine: any = {
        int_rec_id: 0, // Assuming the ID is auto-generated by the backend
        var_item_name: this.addForm.get('name')!.value,
        var_manufacturer_name: this.addForm.get('manufacturer')!.value,
        dec_price: this.addForm.get('price')!.value,
        dtm_creationdate: new Date().toISOString(), // Current date and time
        dtm_expirydate: this.addForm.get('expiryDate')!.value,
        int_status_id: 1 // Assuming a default status ID
      };

      this.medicineService.addMedicine(newMedicine).subscribe(() => {
        // alert('Medicine added successfully!');
        this.router.navigate(['/list']);
      });
    }
  }
}